{"name": "CVE-2015-0222", "public_date": "2015-01-13T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:6"}], "acknowledgement": "\nRed Hat would like to thank the upstream Django project for reporting this issue.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "Django 1.7.3, Django 1.6.10", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1179685", "description": "\nCVE-2015-0222 Django: database denial of service with ModelMultipleChoiceField\n    ", "id": "1179685"}, "references": ["\nhttps://www.djangoproject.com/weblog/2015/jan/13/security/\n    "], "details": ["\nModelMultipleChoiceField in Django 1.6.x before 1.6.10 and 1.7.x before 1.7.3, when show_hidden_initial is set to True, allows remote attackers to cause a denial of service by submitting duplicate values, which triggers a large number of SQL queries.\n    "], "cwe": "CWE-20", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P", "status": "draft", "cvss_base_score": "4.3"}}