{"name": "CVE-2017-10788", "public_date": "2017-06-08T00:00:00", "package_state": [{"fix_state": "New", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "rh-perl520-perl-DBD-MySQL", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "New", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "rh-perl524-perl-DBD-MySQL", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "New", "product_name": "Red Hat Enterprise Linux 5", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "New", "product_name": "Red Hat Enterprise Linux 6", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "New", "product_name": "Red Hat Enterprise Linux 7", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1467600", "description": "\nCVE-2017-10788 perl-DBD-MySQL: Use-after-free when calling mysql_stmt_error() after mysql_stmt_close()\n    ", "id": "1467600"}, "details": ["\nThe DBD::mysql module through 4.043 for Perl allows remote attackers to cause a denial of service (use-after-free and application crash) or possibly have unspecified other impact by triggering (1) certain error responses from a MySQL server or (2) a loss of a network connection to a MySQL server. The use-after-free defect was introduced by relying on incorrect Oracle mysql_stmt_close documentation and code examples.\n    "], "cwe": "CWE-416", "cvss3": {"status": "draft", "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H", "cvss3_base_score": "5.9"}}