{"name": "CVE-2016-2513", "affected_release": [{"advisory": "RHSA-2016:0502", "release_date": "2016-03-24T00:00:00", "cpe": "cpe:/a:redhat:openstack:5::el6", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package": "python-django-1.6.11-5.el6ost"}, {"advisory": "RHSA-2016:0506", "release_date": "2016-03-24T00:00:00", "cpe": "cpe:/a:redhat:openstack:5::el7", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 7", "package": "python-django-1.6.11-5.el7ost"}, {"advisory": "RHSA-2016:0505", "release_date": "2016-03-24T00:00:00", "cpe": "cpe:/a:redhat:openstack:6::el7", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package": "python-django-1.6.11-5.el7ost"}, {"advisory": "RHSA-2016:0504", "release_date": "2016-03-24T00:00:00", "cpe": "cpe:/a:redhat:openstack:7::el7", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7", "package": "python-django-1.8.11-1.el7ost"}, {"advisory": "RHSA-2016:0503", "release_date": "2016-03-24T00:00:00", "cpe": "cpe:/a:redhat:openstack-optools:7::el7", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 Operational Tools for RHEL 7", "package": "python-django-1.6.11-5.el7ost"}], "public_date": "2016-03-01T00:00:00", "package_state": [{"fix_state": "Will not fix", "product_name": "Red Hat Ceph Storage 1.2", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:1.2"}, {"fix_state": "Will not fix", "product_name": "Red Hat Ceph Storage 1.3", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:1.3"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 8.0 Operational Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:8"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:8"}, {"fix_state": "Affected", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "Django", "cpe": "cpe:/a:redhat:rhel_sam:1"}], "acknowledgement": "\nRed Hat would like to thank the Django project for reporting this issue.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "python-django 1.8.10, python-django 1.9.3", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1311438", "description": "\nCVE-2016-2513 python-django: User enumeration through timing difference on password hasher work factor upgrade\n    ", "id": "1311438"}, "references": ["\nhttps://www.djangoproject.com/weblog/2016/mar/01/security-releases/\n    "], "details": ["\nThe password hasher in contrib/auth/hashers.py in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack involving login requests.\n    ", "\nA timing attack flaw was found in the way Django's PBKDF2PasswordHasher performed password hashing. Passwords hashed with an older version of PBKDF2PasswordHasher used less hashing iterations, and thus allowed an attacker to enumerate existing users based on the time differences in the login requests.\n    "], "cwe": "CWE-385", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:P/I:N/A:N", "status": "verified", "cvss_base_score": "4.3"}}