{"name": "CVE-2013-1665", "affected_release": [{"advisory": "RHSA-2013:0596", "release_date": "2013-03-05T00:00:00", "cpe": "cpe:/a:redhat:openstack:2::el6", "product_name": "OpenStack Folsom", "package": "openstack-keystone-2012.2.3-3.el6ost"}, {"advisory": "RHSA-2013:0657", "release_date": "2013-03-21T00:00:00", "cpe": "cpe:/a:redhat:openstack:2::el6", "product_name": "OpenStack Folsom", "package": "openstack-nova-2012.2.3-4.el6ost"}, {"advisory": "RHSA-2013:0658", "release_date": "2013-03-21T00:00:00", "cpe": "cpe:/a:redhat:openstack:2::el6", "product_name": "OpenStack Folsom", "package": "openstack-cinder-2012.2.3-4.el6ost"}, {"advisory": "RHSA-2013:0670", "release_date": "2013-03-21T00:00:00", "cpe": "cpe:/a:redhat:openstack:2::el6", "product_name": "OpenStack Folsom", "package": "Django14-1.4.4-1.el6ost"}], "public_date": "2013-02-19T00:00:00", "package_state": [{"fix_state": "Affected", "product_name": "RHOS Essex Release", "package_name": "Django14", "cpe": "cpe:/a:redhat:openstack:1"}, {"fix_state": "Affected", "product_name": "RHOS Essex Release", "package_name": "openstack-keystone", "cpe": "cpe:/a:redhat:openstack:1"}, {"fix_state": "Affected", "product_name": "RHOS Essex Release", "package_name": "openstack-nova", "cpe": "cpe:/a:redhat:openstack:1"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux 5", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux 6", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux 7", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=912982", "description": "\nCVE-2013-1665 Python xml bindings: External entity expansion in Python XML libraries inflicts potential security flaws and DoS vulnerabilities\n    ", "id": "912982"}, "details": ["\nThe XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex and Folsom, Django, and possibly other products allow remote attackers to read arbitrary files via an XML external entity declaration in conjunction with an entity reference, aka an XML External Entity (XXE) attack.\n    "], "statement": "\nThis issue affects the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7. Red Hat Product Security has rated this issue as having Moderate security impact. This issue is not currently planned to be addressed in future updates.\n    ", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:P/I:N/A:P", "status": "verified", "cvss_base_score": "5.8"}}