{"name": "CVE-2013-2099", "affected_release": [{"advisory": "RHSA-2014:1690", "release_date": "2014-10-22T00:00:00", "cpe": "cpe:/a:redhat:openstack:4::el6", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package": "python-backports-ssl_match_hostname-3.4.0.2-1.el6"}, {"advisory": "RHSA-2015:0042", "release_date": "2015-01-13T00:00:00", "cpe": "cpe:/a:redhat:rhel_common:6::el6", "product_name": "Red Hat Common for Red Hat Enterprise Linux 6", "package": "python-backports-ssl_match_hostname-3.4.0.2-1.el6"}, {"advisory": "RHSA-2016:1166", "release_date": "2016-05-31T00:00:00", "cpe": "cpe:/a:redhat:rhel_software_collections:2::el6", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6", "package": "python27-python-pymongo-3.2.1-1.el6"}, {"advisory": "RHSA-2016:1166", "release_date": "2016-05-31T00:00:00", "cpe": "cpe:/a:redhat:rhel_software_collections:2::el7", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7", "package": "python27-python-pymongo-3.2.1-1.el7"}, {"advisory": "RHSA-2014:1263", "release_date": "2014-09-18T00:00:00", "product_name": "Red Hat Storage Console 2.1", "cpe": "cpe:/a:redhat:storage:2.1:console:el6"}, {"advisory": "RHSA-2014:1263", "release_date": "2014-09-18T00:00:00", "cpe": "cpe:/a:redhat:storage:2.1:server:el6", "product_name": "Red Hat Storage Server 2.1", "package": "python-backports-ssl_match_hostname-3.4.0.2-1.el6"}, {"advisory": "RHSA-2014:1263", "release_date": "2014-09-18T00:00:00", "cpe": "cpe:/a:redhat:storage:2:client:el5", "product_name": "Red Hat Storage Native Client for Red Hat Enterprise Linux 5", "package": "glusterfs-3.4.0.68rhs-1.el5"}, {"advisory": "RHSA-2014:1263", "release_date": "2014-09-18T00:00:00", "cpe": "cpe:/a:redhat:storage:3:client:el6", "product_name": "Red Hat Storage Native Client for Red Hat Enterprise Linux 6", "package": "glusterfs-3.4.0.68rhs-1.el6"}], "public_date": "2013-05-15T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Enterprise MRG 2", "package_name": "pymongo", "cpe": "cpe:/a:redhat:enterprise_mrg:2"}, {"fix_state": "Affected", "product_name": "Red Hat Satellite 6", "package_name": "python-backports-ssl_match_hostname", "cpe": "cpe:/a:redhat:network_satellite:6"}, {"fix_state": "Affected", "product_name": "Red Hat Satellite 6", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:network_satellite:6"}, {"fix_state": "Affected", "product_name": "Red Hat OpenShift Enterprise 2", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:openshift:2"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux OpenStack Platform 3.0", "package_name": "python-backports-ssl_match_hostname", "cpe": "cpe:/a:redhat:openstack:3"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:openstack:4"}, {"fix_state": "Affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-backports-ssl_match_hostname", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:openstack:6"}, {"fix_state": "Affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7", "package_name": "python-pymongo", "cpe": "cpe:/a:redhat:openstack:7"}, {"fix_state": "Not affected", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "pymongo", "cpe": "cpe:/a:redhat:rhel_sam:1"}, {"fix_state": "Not affected", "product_name": "Red Hat Software Collections 1 for Red Hat Enterprise Linux", "package_name": "python33-python", "cpe": "cpe:/a:redhat:rhel_software_collections:1"}, {"fix_state": "Not affected", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "rh-python34-python-pymongo", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "Will not fix", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "python33-python-pymongo", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "bzr", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Fix deferred", "product_name": "Red Hat Enterprise Linux 7", "package_name": "bzr", "cpe": "cpe:/o:redhat:enterprise_linux:7"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "python-tornado", "cpe": "cpe:/o:redhat:enterprise_linux:7"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "acknowledgement": "\nThis issue was discovered by Florian Weimer (Red Hat Product Security).\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Low", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=963260", "description": "\nCVE-2013-2099 python: ssl.match_hostname() DoS via certificates with specially crafted hostname wildcard patterns\n    ", "id": "963260"}, "details": ["\nAlgorithmic complexity vulnerability in the ssl.match_hostname function in Python 3.2.x, 3.3.x, and earlier, and unspecified versions of python-backports-ssl_match_hostname as used for older Python versions, allows remote attackers to cause a denial of service (CPU consumption) via multiple wildcard characters in the common name in a certificate.\n    ", "\nA denial of service flaw was found in the way Python's SSL module implementation performed matching of certain certificate names. A remote attacker able to obtain a valid certificate that contained multiple wildcard characters could use this flaw to issue a request to validate such a certificate, resulting in excessive consumption of CPU.\n    "], "statement": "\nNot vulnerable. This issue did not affect the versions of python as shipped with Red Hat Enterprise Linux 5 and 6 as the SSL module there did not implement the match_hostname() routine yet.\n    ", "cwe": "CWE-407", "cvss": {"cvss_scoring_vector": "AV:N/AC:H/Au:N/C:N/I:N/A:P", "status": "verified", "cvss_base_score": "2.6"}}